-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Oct 12, 2025 at 08:15 PM
-- Server version: 11.8.3-MariaDB-log
-- PHP Version: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


--
-- Dumping data for table 
--

INSERT INTO  (`user_id`, `user_login`, `user_email`, `full_name`, `job_title`, `company`, `country`, `talk_title`, `talk_description`, `talk_time`, `bio`, `photo_url`, `social_media_linkedin`, `social_media_twitter`, `social_media_website`) VALUES
('user_id', 'user_login', 'user_email', 'full_name', 'job_title', 'company', 'country', 'talk_title', 'talk_description', 'talk_time', 'bio', 'photo_url', 'social_media_linkedin', 'social_media_twitter', 'social_media_website'),
('22', 'bahija.maala@shanti.tn', 'bahija.maala@shanti.tn', 'Bahija Maalla', 'Marketing Communication Manager', 'Shanti', 'Tunisia', 'Panel 3:  MSMEs’ Export Readiness: strengthening Business Development Services, business community and entrepreneurship ecosystems ', '', '2025-05-13 09:30:00', 'A trailblazer in Tunisia’s startup ecosystem, Bahija transforms local ideas into global ventures through tailored incubation and business development services. Her work empowers entrepreneurs to scale, innovate, and compete globally.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Bahija-Maalla.png', 'https://www.linkedin.com/in/bahija-moalla-2aa01118a/', '', ''),
('39', 'diaa@agricash.app', 'diaa@agricash.app', 'Dr. Diaa Youssef', 'CEO', 'AgriCash ', '', 'Panel 2: Financing Global Trade and Inclusive Solutions for MSMEs: take aways from Egypt', '', '2025-05-12 00:30:00', 'At the forefront of AgriFintech, Dr. Youssef is redefining access to credit for rural MSMEs. His work with AgriCash strengthens the bridge between agriculture and digital finance, uplifting smallholder farmers and rural entrepreneurs through innovative solutions.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Diaa-Youssef.png', 'https://www.linkedin.com/in/diaayousef/', '', 'https://agricash.app/contact/'),
('80', 'lamiaaplpl@yahoo.com', 'lamiaaplpl@yahoo.com', 'Lamia Saleh', ' Founder & CEO, Smart Farmer & Agritech Expert', 'الجيل الخامس ', '', 'Panel 3: MSMEs’ Export Readiness: strengthening Business Development  Services, business community and entrepreneurship ecosystems ', 'عن الشراكات وفرص التصدير الواعده في منطقه صعيد مصر ', '2025-05-13 09:30:00', 'An advocate for innovation in agriculture, Dr. Lamia merges sustainability with technology to digitize and globalize agri-MSMEs. Through Smart Farmer, she opens new markets for farmers while enhancing food security and resilience in the sector.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Lamia-Saleh.png', 'https://www.linkedin.com/in/لمياء-صلاح-b253b9251', '', 'https://www.facebook.com/share/15trEPbkBM/'),
('103', 'ostermeier@ilo.org', 'ostermeier@ilo.org', 'Martin Ostermeier', 'Chief Technical Advisor', ' ILO Cairo', 'Germany', 'Panel 1:  Strategic Policies for Enhancing Trade Dynamics and Employment creation', '', '2025-05-12 11:00:00', 'Economist with a PhD from the University of Göttingen, He leads the EU-funded METI project at the ILO, driving the integration of employment into trade and investment strategies.\r\n', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Martin.png', 'https://www.linkedin.com/in/martin-ostermeier-057468b2?utm_source=share&amp;utm_campaign=share_via&amp;utm_content=profile&amp;utm_medium=android_app', '', 'www.ilo.org/meti'),
('104', 'maher.abougabal@gmail.com', 'maher.abougabal@gmail.com', 'Maher Abou Gabal', 'Secretary of the Foreign Relations Committee', ' the Arab Union of Agricultural Engineers Arab League', '', 'Panel 1:  Strategic Policies for Enhancing Trade Dynamics and Employment creation', '', '2025-05-12 11:00:00', 'Secretary of the Foreign Relations Committee, Rapporteur\r\nof the Permanent Committee for Investment, Advisor to the General Secretariat\r\nof the Arab Union of Agricultural Engineers Arab League', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Group-40726.png', 'https://www.linkedin.com/in/maher-abou-gabal-4b86b555/', '', ''),
('105', 'jane.g.hanna@gmail.com', 'jane.g.hanna@gmail.com', 'Jane G. Hanna', 'Director of Partnerships and Programmes', 'The Arab Academy Entrepreneurship Center', 'Egypt', 'Moderator', '', '', 'With a dynamic background in entrepreneurship, innovation, and ecosystem building, Jane brings years of experience leading impactful programs across the MENA region.\r\nAs Director of Programmes and Partnerships at The Arab Academy Entrepreneurship Center and Manager of the Ripple Summit, she’s a powerhouse of collaboration and innovation.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Jane-Hanna.png', 'https://www.linkedin.com/in/jane-g-hanna/', '', ''),
('106', 'dalia.abdallah@aucegypt.edu', 'dalia.abdallah@aucegypt.edu', 'Dalia Abd Allah', 'Senior Director ', 'AUC- Innovation Hub', 'Egypt', 'Panel 1:  Strategic Policies for Enhancing Trade Dynamics and Employment creation', '', '2025-05-12 11:00:00', 'With 20+ years in innovation and SME support, she has led $50M+ in investments, created 1,500+ jobs, and fostered economic growth through policy and international cooperation.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Dalia-Abd-Allah-1.png', '', '', ''),
('107', 'nevine@elgondytrading.com', 'nevine@elgondytrading.com', 'Nevine Nabil Nakhla ', 'CEO', 'El Gondy Trading - AfCFTA Trading Company Egypt', 'Egypt', 'MSMEs Export Readiness', 'Panel 3:  MSMEs’ Export Readiness: strengthening Business Development Services, business community and entrepreneurship ecosystems ', '2025-05-13 09:30:00', 'Dr. Nevine N. Nakhla has 20 + years of experience in Import &amp; Export and Distribution. Strategic\r\nmanagement and Marketing is her key areas of strength academically and professionally,\r\nacademically, her Doctorate Degree in Business Administration, Thesis “The impact of\r\nEntrepreneurs marketing capabilities on their international performance”, and professionally, as\r\nan Entrepreneur founded her own Organization during 2016, El Gondy Trading with\r\nInternational brands launched in Egypt and the Exportation of diversified goods from different\r\nindustries, as well as strong distribution network in all Egypt, Modern trade Key accounts,\r\npharmacy chains and HORECA. El Gondy Trading is the AFCFTA Trading company\r\nEgypt, as catalyst for improved trade under AFCFTA, with the vision to boost Intra-African\r\nTrading.\r\n\r\nNevine is a Professor of Strategic Management and Marketing in The Arab Academy for Science\r\nand Technology, as well as other esteemed Universities. A Certified mentor to Entrepreneurs\r\n.\r\nNevine, training to Entrepreneurs and youth in Centers of Entrepreneurship in different\r\nInternational and Egyptian Organizations, as the Ministry of Communication and Technology\r\nTraining Faculties, and the Center of Entrepreneurship AUC. A public speaker in Many\r\nEgyptian and International Conferences, contributed to many researches, and a regular speaker in\r\nthe Nile TV the only English-Speaking Egyptian Television Channel.\r\n\r\nNevine is a Board of Directors member of the Egyptian Federation for Mental Development of\r\nyouth Egypt, as well as Assistant Governor and RCC committee Chair in Rotary District Egypt,\r\nas community servicing and working with various Egyptian and International NGOs is part of\r\nher life routine. Nevine is a member in the Egyptian Businessmen Association, and a member in\r\nthe Egyptian African Businessmen Association, and her Company El Gondy Trading is ISO\r\nCertified and a white list in the Food Export Council.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Nevine-Nabil-Nakhla.png', 'https://www.linkedin.com/in/nevine-nakhla-13851914?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BGPwKXpdBRhat0FiyFAC4%2Fw%3D%3D', '', 'http://www.elgondytrading.com/'),
('109', 'sassem@expolink.org', 'sassem@expolink.org', 'Sherine Assem', ' Handicrafts Sector Director', ' Egyptian Exporters Association \"Expolink', 'Egypt', 'Panel 3:  MSMEs’ Export Readiness: strengthening Business Development Services, business community and entrepreneurship ecosystems ', '', '2025-05-13 09:30:00', 'A visionary in trade and investment, Sherine builds strong bridges between MENA and European markets. With deep expertise in streamlining trade frameworks, she turns investment into opportunity.\r\nBuilding strong market connections.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Sherine-Assem-1.png', '', '', ''),
('110', 'mabdelkarim@hivos.org', 'mabdelkarim@hivos.org', 'Mariam AbdelKarim', 'Business Development Manager - MENA', 'Hivos ', '', 'Panel 3:  MSMEs’ Export Readiness: strengthening Business Development Services, business community and entrepreneurship ecosystems ', '', '2025-05-13 09:30:00', 'Championing inclusive development, Mariam builds the capacity of MSMEs to grow, export, and drive social impact across MENA. Her regional approach fosters economic empowerment, community transformation, and sustainable trade linkages.\r\n', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Frame-404.png', '', '', ''),
('111', 'moabdulaziz707@gmail.com', 'moabdulaziz707@gmail.com', 'Mohamed abd el Aziz', 'CEO', 'B2B Market place, Egypt', 'Egypt', 'Panel 3:  MSMEs’ Export Readiness: strengthening Business Development Services, business community and entrepreneurship ecosystems ', '', '2025-05-13 09:30:00', 'Mohamed is revolutionizing regional trade logistics, positioning Egypt as a digital gateway for B2B commerce across Africa, MENA, and Europe.\r\n🛒 Trade faster. Trade smarter. Trade beyond borders.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Mohamed-abd-el-Aziz.png', '', '', ''),
('112', 'ms@mentorsis.com', 'ms@mentorsis.com', 'Mohamed El Sery', 'CEO, Mentors\' Business Community', 'International Canadian Chamber of Commerce', 'Egypt', 'Panel 3:  MSMEs’ Export Readiness: strengthening Business Development Services, business community and entrepreneurship ecosystems ', '', '2025-05-13 09:30:00', 'Dr. Serri connects MSMEs with global mentors and networks to support sustainable growth through knowledge, access, and credibility.\r\nEcosystems grow when businesses connect.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Mohamed-El-Sery.png', '', '', ''),
('113', 'dima.chehabeddine83@gmail.com', 'dima.chehabeddine83@gmail.com', 'Mrs. Dima Chehabedine', 'Agri-business Expert', 'Minister of Economy & Trade, Lebanon', 'Lebanon', 'Panel 1:  Strategic Policies for Enhancing Trade Dynamics and Employment creation', '', '2025-05-12 11:00:00', 'With 15+ years in agri-food policy, Dima bridges farm-to-trade strategies to boost exports, empower SMEs, and advance food security in MENA. From EU projects to ministry advising, she turns policy into impact.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Dima-Chehabedine.png', '', '', ''),
('114', 'margreetmagdy@hotmail.com', 'margreetmagdy@hotmail.com', 'Margreet Magdy', 'Founder / Board Member ', 'You are س / Youth Entrepreneurs Network ', '', 'Investor Pitch Clinic', '', '2025-05-12 15:30:00', 'Margreet Magdy is an Ecosystem Builder, Entrepreneurial Strategist &amp; Inclusive Innovation Advocate\r\n\r\nMargreet Magdy is an expert in entrepreneurship development, startup strategy, and inclusive ecosystem building, with over 15 years of experience designing and leading transformative programs across the MENA region. Her work spans global accelerators, EU- and USAID-funded initiatives, and regional innovation platforms, where she has supported hundreds of startups in areas including investment readiness, digital transformation, and strategic growth.\r\n\r\nShe is the founder of You Are س, a regional initiative focused on women’s economic empowerment, and a founding board member of the Youth Entrepreneurs Network, where she champions youth-led innovation and grassroots entrepreneurship.\r\n\r\nThrough her extensive mentorship with organizations like Google for Startups, the European Innovation Council, DIFC’s Leap, and VC4A, Margreet has become known for her ability to translate complex challenges into clear, scalable strategies that help startups grow, raise capital, and expand into new markets. Her approach integrates gender equity, sustainability, and data-informed decision-making as pillars of resilient entrepreneurship.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Margreet-Magdy.png', 'http://linkedin.com/in/margreet-magdy', '', 'www.youareseen.net'),
('116', 'assem@seketak-eg.com', 'assem@seketak-eg.com', 'Assem Kamel ', 'CEO', 'SEKETAK Entrepreneurship Solutions', '', 'Panel 1:  Strategic Policies for Enhancing Trade Dynamics and Employment creation', '', '2025-05-12 11:00:00', 'A visionary leader with 20+ years of experience in socioeconomic and driving growth in MENA. Co-founded startups, designed programs, and ensured global impact.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Assem-Kamel.png', '', '', ''),
('117', 'manal@seketak-eg.com', 'manal@seketak-eg.com', 'Manal Hassoun', ' Financial inclusion expert & CFPO', 'SEKETAK Solutions', 'Lebanon', ' Panel 2: Financing Global Trade and Inclusive Solutions for MSMEs:  take aways from Egypt', ' Gender-Lens Financial Inclusion', '2025-05-12 12:30:00', 'Manal Hassoun is an Senior Expert on financial inclusion, gender equality, socio-economic development, and strategic business growth. With over 24 years of extensive experience spanning Lebanon, Jordan, Syria, Egypt, Tunisia, Morocco, Yemen, and Iraq, she has established herself as a trusted authority in driving transformative change across diverse markets and challenging environments. \r\n\r\nManal, a certified microfinance expert from the Frankfurt School of Finance and Management, holds accreditations across numerous national, regional, and international programs. Her commitment to advancing gender equity and women’s empowerment is demonstrated through her role as a UN-accredited Gender Auditor and UNDP MENA Women Mentor. She also holds a Leadership Management International Licensee for the Arab region, highlighting her expertise in leadership development and organizational excellence.\r\n\r\nManal\'s leadership in empowering women is a shining example of success. She has co-founded multiple women-led businesses in Lebanon and Egypt, and her strategic planning, operations planning,  entrepreneurship, leadership, employment development, and financial inclusion initiatives have helped many microfinance institutions &amp; Startups in Lebanon, Egypt, Iraq, and Yemen.\r\n\r\n Manal has led projects with a portfolio of over $20M+ targeting young women in post-conflict and refugee settings. Her work with international organizations and UN agencies such as the World Bank Group, IFC, ILO, UNICEF, UNFPA, USAID, GIZ, Sanabel Microfinance network has made a significant impact.\r\nA visionary in human capital development, Manal has Developed and certified over 2,000 Trainers &amp; Coaches in MENA regions and 15,000 employees from CEOs, Senior managers, Middle managers, juniors, and enterprises. \r\n\r\nThroughout the years, Manal developed and adapted many business strategies, learning curricula, and building programs in microfinance, business, &amp; personal development. ', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Manal-Hassoun.png', 'https://www.linkedin.com/in/manal-hassoun-81518018/', '', ''),
('118', 'ngharbi@cdc.tn', 'ngharbi@cdc.tn', 'Nejia Gharbi', 'General Director', 'Caisse des Dépôts et Consignations Tunisie', 'Tunisia', 'Panel 1:  Strategic Policies for Enhancing Trade Dynamics and Employment creation', '', '2025-05-12 11:00:00', 'With 30+ years in public finance, she is DG of CDC and Chair of CDC Gestion and CDC Développement. Former Chair of BNA and STB, she is an ENA graduate and PPP-certified by APMG/World Bank.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/nejia-gharbi.png', '', '', ''),
('119', 'rasha.yousry@cbe.org.eg', 'rasha.yousry@cbe.org.eg', 'Rasha Yousri ', 'Head of Micro and Small Businesses', ' Central Bank of Egypt', 'Egypt', 'Panel 2: Financing Global Trade and Inclusive Solutions for MSMEs: take aways from Egypt', '', '2025-05-12 12:30:00', 'Head of Micro and Small Businesses, Central Bank of Egypt\r\nA pillar of Egypt’s MSME strategy, Dr. Yousri brings 22 years of expertise at the CBE, including 7 years dedicated to enabling financial and non-financial support ecosystems for micro and small businesses through national collaboration.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Rasha-Yousri.png', '', '', ''),
('120', 'ali.saad@msmef-eg.org', 'ali.saad@msmef-eg.org', 'Ali Saad', 'General Manager', 'Egyptian Federation for MSME Financing', 'Egypt', 'Panel 2: Financing Global Trade and Inclusive Solutions for MSMEs:  take aways from Egypt', '', '2025-05-12 12:30:00', 'With 26 years of experience, Ali is a foundational figure in Arab microfinance. He has developed cross-border frameworks and organized over 50 major conferences—amplifying inclusive finance policies at scale.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Ali-Saad.png', '', '', ''),
('121', 'dtakla@tamweely.com.eg', 'dtakla@tamweely.com.eg', 'Dalal Takla', 'Chief Business Excellence Officer', 'Tamweely for Microfinance', 'Egypt', 'Panel 2: Financing Global Trade and Inclusive Solutions for MSMEs: take aways from Egypt', 'Financial inclusion is a trade enabler. Inclusive financing—tailored to the realities of small and women-led businesses—is the key to unlocking investment, increasing exports, and building resilient cross-Mediterranean trade.', '2025-05-12 12:30:00', 'I am a strategic, results-oriented Chief Business Excellence Officer with a broad and deep background across all facets of the financial services industry. Recognized for consistently delivering impactful business outcomes, I was honored among the \'Top 50 Most Influential Women in Egypt.\' With over 30 years of experience, I have built a distinguished career specializing in non-banking financial services and microfinance. Currently, I serve as the Chief Business Excellence Officer at Tamweely Microfinance, where I continue to expand my leadership and sectoral expertise.\r\n\r\nIn addition to earning a Doctorate in Business Administration with a focus on Finance and Investment from Ain Shams University, I have gained valuable international experience in leadership, policy development, and microfinance governance. This includes participation in prestigious study tours and training programs sponsored by the U.S. Department of State and institutions in countries such as Italy (Boulder Turin), Cambodia, the Philippines, Uganda, and others.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Dalal-Takla.png', 'https://www.linkedin.com/in/dalal-takla-31329026/', '', 'Tamweely.com.eg'),
('122', 'Shymaa.allam@gmail.com', 'Shymaa.allam@gmail.com', 'Shymaa Bedaiwy', 'Financial Inclusion & Women’s Economic Empowerment Expert', ' University of Massachusetts Boston.', 'Boston', 'Panel 2: Financing Global Trade and Inclusive Solutions for MSMEs: take aways from Egypt', '', '2025-05-12 00:30:00', 'Financial Inclusion & Women’s Economic Empowerment Expert\r\nAs Egypt’s first female microfinance regulator at the FRA and a PhD researcher at UMass Boston, Dr. Bedaiwy blends policy advocacy with academic excellence. Her expertise in feminist finance and inclusive systems makes her a leading voice in shaping equitable access to finance.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Shymaa-Bedaiwy.png', '', '', ''),
('123', 'douja.gharbi@redstart.tn', 'douja.gharbi@redstart.tn', 'Douja Gharbi', 'CEO', ' RedStart Tunisia Accelerator', 'Tunisia', 'Panel 3:  MSMEs’ Export Readiness: strengthening Business Development Services, business community and entrepreneurship ecosystems ', '', '2025-05-13 09:30:00', 'From policy to grassroots, Douja brings a global lens to MSME development. Through decent work strategies, she transforms local businesses into export-ready players.\r\nStrengthening systems. Creating jobs. Driving trade.', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Douja-Gharbi.png', '', '', ''),
('243', 'miguel@afrilabs.com', 'miguel@afrilabs.com', 'Miguel  Nyamedi ', 'Member Services Associate', 'AfriLabs – African Technology and Innovation Initiative ', 'Togo', '', '', '', 'Miguel Nyamedi is a professional with over 8 years of experience across 8 countries, \r\nincluding Togo, Côte d\'Ivoire, Liberia, Bangladesh, Burkina Faso, Benin, and Nigeria. \r\nHe is certified in Global Business Expansion, Innovation, Community and Network \r\nEngagement, Entrepreneurship, and Talent and Global Leadership Development. \r\nCurrently serving as the *Member Services Associate at AfriLabs*, a Pan-African \r\nnetwork organization supporting the growth of over 500 innovation and technology \r\nhubs across 53 African countries, Miguel plays a key role in contributing in the \r\ncommunity expansion and engagement to strengthen Africa’s innovation \r\necosystem', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Miguel_Nyamedi_Photo-002.png', '', '', ''),
('252', 'Yousef Fennira', 'fennira@ilo.org', 'Yousef Fennira', 'Chief Technical Advisor, Head Cluster  Enterprise', 'ILO Office Tunisia', 'Tunisia', '', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Yousef-Fennira.png', '', '', ''),
('253', 'Christophe Malherbe', 'cmalherbe@factfund.com', 'Christophe Malherbe', 'MSME Financing II - Team Leader', 'KFW-EU funded project', 'France', '', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Group-40830.png', '', '', ''),
('254', 'Dhouha Chouikh', 'd.chouikh@diplomatie.gov.tn', 'Dhouha Chouikh', 'Minister Plenipotentiary, in charge of cooperation', 'The Tunisian Embassy in Egypt', 'Egypt', '', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/05/Group-40832.png', '', '', ''),
('348', 'T.TRAORE@unido.org', 'T.TRAORE@unido.org', 'M. Tièmoko TRAORE', 'Coordinateur National du projet', ' Industrie 4.0 to foster youth employment', 'Côte d’Ivoire', 'Préparation des MPME à l\'exportation : renforcement des services de développement des entreprises, de la communauté des affaires et des écosystèmes entrepreneuriaux ', '', '', 'Coordinateur National du projet Industrie 4.0 to foster youth employment in Tunisia and Côte d’Ivoire – ONUDI', 'https://gits.seketak-eg.com/wp-content/uploads/2025/06/Frame-413.png', '', '', ''),
('449', 'sackhopatel@ilo.org', 'sackhopatel@ilo.org', 'Djitaba Ouleymatou Sackho-Patel', ' Responsable technique en finance solidaire', 'OIT Côte d’Ivoire', 'Côte d’Ivoire', 'Panel 2: L’accès au financement, levier pour un meilleur accès au marché: expériences croisées', '', '', ' Responsable technique en finance solidaire, OIT Côte d’Ivoire', 'https://gits.seketak-eg.com/wp-content/uploads/2025/06/Mme-Djitaba-Ouleymatou-Sackho-Patel.png', '', '', 'sackhopatel@ilo.org'),
('450', 'chroud@ilo.org', 'chroud@ilo.org', 'Faiçal Chroud', 'Coordinateur National de projet', 'OIT Tunisie', 'Tunisia', 'Panel 2: L’accès au financement, levier pour un meilleur accès au marché: expériences croisées', '', '', 'Coordinateur National de projet,OIT Tunisie\r\n', 'https://gits.seketak-eg.com/wp-content/uploads/2025/06/M.Faical-Chroud.png', '', '', 'chroud@ilo.org'),
('452', 'Fabrice Adelphe BALOU', 'fabrice.adelphe.balou@mail.com', 'Fabrice Adelphe BALOU', 'Gérant Principal de ABEWE, Responsable du pôle Jeun\'ESS du GSEF', 'Global Social Economic Forum', 'Côte d’Ivoire', 'Panel 1: Préparation des MPME à l\'exportation : renforcement des services de développement des entreprises, de la communauté des affaires et des écosystèmes entrepreneuriaux', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/07/Fabrice-Adelphe-BALOU.png', '', '', ''),
('453', 'Stifani Machmouchi', 'stifani.machmouchi@mail.com', 'Stifani Machmouchi', 'designer éco-responsable et CEO de Stifani Machmouchi Architecture & Design', 'Stifani Machmouchi Architecture & Design', 'Côte d’Ivoire', 'Panel 1: Préparation des MPME à l\'exportation : renforcement des services de développement des entreprises, de la communauté des affaires et des écosystèmes entrepreneuriaux ', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/07/Stifani-Machmouchi.png', '', '', ''),
('454', 'Benjamin WALKER', 'benjamin.walker@mail.com', 'Benjamin WALKER', 'Directeur de Développement des Marchés', 'Côte d\'Ivoire Export', 'Côte d’Ivoire', 'Panel 1: Préparation des MPME à l\'exportation : renforcement des services de développement des entreprises, de la communauté des affaires et des écosystèmes entrepreneuriaux ', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/07/Benjamin-WALKER.png', '', '', ''),
('455', 'KOFFI Paul Agenor', 'koffi.paul.agenor@mail.com', 'KOFFI Paul Agenor', 'Coordonnateur National de Projet du Projet ACCEL 2', 'OIT Abidjan', 'Côte d’Ivoire', '', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/07/KOFFI-Paul-Agenor.png', '', '', ''),
('456', 'Vaflahi Meite', 'vafmeite@gmail.com', 'Vaflahi Meite', 'Directeur Général de la Diplomatie Economique', 'Ministère des Affaires Etrangères, Côte d’Ivoire', 'Côte d’Ivoire', 'Ouverture Officielle', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/07/Vaflahi-Meite.png', '', '', ''),
('457', 'SE Monsieur Sherif SEIF', 'sherif.seif@mail.com', 'SE Monsieur Sherif SEIF', 'Ambassadeur Extraordinaire et Plénipotentiaire de la République Arabe d\'Egypte en Côte d\'Ivoire', 'République Arabe d\'Egypte en Côte d\'Ivoire', 'Egypt', 'Ouverture Officielle', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/07/SE-Monsieur-Sherif-SEIF.png', '', '', ''),
('458', 'Nabou Fall', 'naboufall@yahoo.fr', 'Nabou Fall', 'Founder-Director ', 'Nabou Fall Academy  CEO, Agence VIZEO', 'Côte d’Ivoire', '', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/07/Nabou-Fall.png', '', '', ''),
('459', 'Lionel YAO', 'lionelyao2007@gmail.com', 'Lionel YAO', 'fondateur de la première nano banque digitale S-Cash', 'S-Cash', 'Côte d’Ivoire', 'Panel 2: L’accès au financement, levier pour un meilleur accès au marché: expériences croisées', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/07/Lionel-YAO.png', '', '', ''),
('460', 'TRAORE SARAN DOUMBIA', 'traore.saran.doumbia@mail.com', 'Traore Saran Doumbia', 'Directrice de la modernisation, de l\'appui aux OPA et du genre sera la représentante de l\'ANADER', 'ANADER', 'Côte d’Ivoire', 'Panel 2: L’accès au financement, levier pour un meilleur accès au marché: expériences croisées', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/07/TRAORE-SARAN-DOUMBIA.png', '', '', ''),
('461', 'Aissata Dicko', 'aissata.dicko@mail.com', 'Aïssata Dicko', 'Cheffe de projet spécialisée dans l’autonomisation des femmes et l’innovation numérique, initiatrice de projets au BabyLab', 'BabyLab', 'Côte d’Ivoire', '', '', '', '', 'https://gits.seketak-eg.com/wp-content/uploads/2025/07/Aissata-Dicko.png', '', '', '');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
